### ISSUE TITLE
maze size bug

### ISSUE THREAD

**Issue by Kanti** [derRest/derRest#11]
x=2,y=2
Aber spielfeld ist 5x7 ??!?
![image](https://cloud.githubusercontent.com/assets/471387/19228675/c41eaafc-8ec7-11e6-96af-aa6fee304ee9.png)

**Comment by schuesslerf** [comment]
quasi behoben, nur minimale Abweichung, Fehler mit Candy Generierung auch behoben

**Comment by Kanti** [comment]
not done jet !

**Comment by schuesslerf** [comment]
now it is
