### ISSUE TITLE
Highscore

### ISSUE THREAD

**Issue by janjj** [derRest/derRest#3]
jeder Level Finish wird getrackt - und wird in Datenbank gespeichert - besten x werden angezeigt

- API definieren, Javascript api ``newHighScore('nameOne',120.09);``

**Comment by schuesslerf** [comment]
jeder Level Finish wird getrackt - und wird in Datenbank gespeichert - besten x werden angezeigt

**Comment by ChrisB9** [comment]
Was sind denn der zweite Parameter?

**Comment by janjj** [comment]
Ich denke mal Punkte. 
vlt 120 candys und 09 Schlüssel ^^

kp

**Comment by ChrisB9** [comment]
kk, vllt dann noch zustzl: elapsedTime und reachedLevel?
