### ISSUE TITLE
Map: Darstellung

### ISSUE THREAD

**Issue by janjj** [derRest/derRest#4]
File von Generierung entgegennehmen und darstellen

**Comment by schuesslerf** [comment]
File von Generierung entgegennehmen und darstellen

**Comment by ChrisB9** [comment]
Wie soll denn die Datei aussehen?

**Comment by janjj** [comment]
ich würde sagen z.B:

| ------------------------ |
| x  |                    |           |
|            |       s                |
| ------------------------ |
X - gleich start oder Mänchen
s - gleich schlüssel/candy

Ist nur n Vorschlag müssen wir mal drüber diskutieren vorallem wie das ist mit dem auslesen etc...
