### ISSUE TITLE
show score live

### ISSUE THREAD

**Issue by schuesslerf** [derRest/derRest#43]
while playing, be able to see current score as well

**Comment by Kanti** [comment]
Sollten wir das Wirklich einbauen? Das macht doch die Spannung zunichte.

**Comment by schuesslerf** [comment]
Dann würde man halt auch sehen wie die Punkte zustande kommen und so

**Comment by janjj** [comment]
Die Punkte vergabe ergibt eh noch nicht so viel Sinn....deswegen wäre das vlt Nachteilig.

Es ist viel zu Arg zeit Fokusiert, die Bonbons werden zu wenig gewertet
Bsp. Durch rasen, mit 7,4 sec. und 1-2 gesammelten bonbons = 42Pkt.
Alle Bonbons sammeln(10) und dafür ca. 30 sec. gibt grade mal 16 Pkt

**Comment by ChrisB9** [comment]
Ich arbeite aktuell noch an einem besseren und logischeren algorithmus bei dem ich alle faktoren einbauen will.
Punkte werden durch:
  - Geschwindigkeit
  - Akkuratesse
  - Menge der Bonbons
  - (Level)
  - Größe des Labyrints
 etc. generiert
die aktuelle version ist ja eher mehr spaßig konstruiert.

**Comment by ChrisB9** [comment]
Was ich denke, was aber sinn ergibt, ist die aktuell gebrauchte Zeit anzuzeigen

**Comment by schuesslerf** [comment]
Zeit läuft weiter (oben in navbar), auch wenn schon fertig gespielt

**Comment by ChrisB9** [comment]
Bei mir in der navbar steht derRest wenn ich fertig gespielt hab, kann ich also nicht reproduzieren

**Comment by ChrisB9** [comment]
öffne es bitte als eigenständigen issue
