### ISSUE TITLE
Installationsproblem

### ISSUE THREAD

**Issue by akramer-dozent** [derRest/derRest#56]
Ich bekomm euer Spiel leider nicht zum laufen.

Hab es mit einem Docker container mit php7 und apache versucht...
https://hub.docker.com/r/eliep/php7-apache/

...leider bringt mir der Webserver den Fehler "404".

Die PHP Version ist:
PHP 7.0.0beta1 (cli) (built: Jul  8 2015 07:16:44) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

Die Apache Version ist:
Server version: Apache/2.4.12 (Fedora)

Der Apache vhost ist wie folgt konfiguriert:
&lt;VirtualHost *:80&gt;
  ServerName localhost
  DocumentRoot /var/www/html
  DirectoryIndex index.html index.php

  &lt;Directory /var/www/html&gt>
    Options FollowSymLinks
    AllowOverride All
    Require all granted
  &lt;/Directory&gt>
  
  &lt;IfModule php7_module&gt>
    php_admin_value variables_order "EGPCS"
    php_admin_value date.timezone "UTC"
  &lt;/IfModule&gt;
  
&lt;/VirtualHost&gt;

Der Request taucht im access_log auf, der error_log bleibt ohne Eintrag.
Das favicon zeigt der Browser auch an.

composer install und npm install sind ohne Fehler durchgelaufen.

Wisst ihr woran es liegen könnte?

**Comment by akramer-dozent** [comment]
<img width="176" alt="404" src="https://cloud.githubusercontent.com/assets/17781068/19697883/6fa8f0f4-9aed-11e6-8837-6938e78782c5.PNG">

**Comment by schuesslerf** [comment]
Also ich seh spontan keinen Fehler, wir nutzen alle Xampp und funtkioniert bei allen ohne Probleme nach npm install und composer install. Vielleicht kannst du das mal mit Xampp versuchen?
Ansonsten läuft aber auch https://lab.cben.co/derRest/ hier das Spiel live.

**Comment by akramer-dozent** [comment]
Danke für dein rasantes Feedback. Ich klicke euer Spiel gerade auf eurem Server durch.
...es wäre für die noch folgenden Aufgaben gut wenn es auch bei mir lokal laufen würde. Ich schaus mir nochmal an und werd es mal mit xampp probieren.

**Comment by schuesslerf** [comment]
Ja, ich sehe schon, 11 Punkte ;) Ja, wie gesagt, vielleicht läuft es mit XAMPP, habe sonst gerade auch noch einen Teamkollegen gefragt, ob er eine Idee hat, vielleicht sieht er noch was.

**Comment by akramer-dozent** [comment]
Ok. Bin mit den Akzeptanztests durch. Mich wundert es nur wie es in dem Spiel jemand schafft 1000 Punkte zu holen ohne zu schummeln ;D

**Comment by schuesslerf** [comment]
Das sind initiale Daten beim erstellen der DB eingetragen werden, sind nicht ganz realistisch aber wird wahrscheinlich noch angepasst, die kamen von der Zeit, bevor die Formel zur Berechnung der Punkte stand.

**Comment by akramer-dozent** [comment]
Ist OK.

**Comment by ChrisB9** [comment]
Was für einen Eintrag hast du im access_log als get
Was sagt die Developer Console im Network und in der Console an sich, irgendwelche Fehlermeldungen?

**Comment by ChrisB9** [comment]
Schau auch mal nach, ob du die richtige Version von node und npm installiert hast
- npm -v : 3.10.X
- node -v : 6.7.X

**Comment by ChrisB9** [comment]
Ich hab es gerade mit dem selben Docker auch mal bei mir probiert.
Meine vermutung:
- Fehler in der httpd/conf/httpd.conf
- Fehler in der .htaccess
--- 
Interessant ist, selbst wenn ich den Ordner auf /var/www/html + AllowOverride All ummappe bekomme ich den 404er
+ mod_rewrite ist standardmäßig aktiviert
Zusatzinfo: 
Die GET-Variable ist leer, wenn sie beim Router ankommt. Wenn man den Router so einstellt, dass er auf leere GET's reagiert, dann wird man tatsächlich weitergeleitet. In folge dessen sind alle anderen Dateien nicht nachladbar, da die baseurl überhaupt nicht stimmt (Verweis auf Fehlerhafte .htaccess / ServerName). Er versucht zum Beispiel ein Request nach http://frontend/js/maze.js auszuführen der natürlich! ins leere läuft [ERR_NAME_NOT_RESOLVED]
--> Eindeutig Konfigurationsfehler in dem Fall, die Frage ist da nur, welcher?

**Comment by ChrisB9** [comment]
Und zum Thema XAMPP:
-> Es nutzen nicht alle xampp!
Mein Server und Ich nutzen es nicht (wäre ja auch auf einem unix-system schwachsinnig). 
Und da es ja auf dem Server läuft, hat es nichts mit "es läuft ja auf xampp" zu tun :) (halt auch in betrachtnahme meines vorherigen kommentars)

**Comment by schuesslerf** [comment]
Stimmt, nur auf unseren Windows Rechnern läuft XAMPP, worauf ich aber hinaus will (erst recht wenn du jetzt sagst dass es bei 2 Leuten mit dem Dicker Container nicht geht, ist, dass es bei XAMPP alles direkt funktioniert hat, dass heißt XAMPP hat dann andere Einstellungen, die bewirken, dass alles funktioniert. Also wäre wahrscheinlich die einfachste Lösung XAMPP zu nutzen

**Comment by schuesslerf** [comment]
*Docker Container

**Comment by akramer-dozent** [comment]
Danke, dass ihr euch noch so viel Mühe gemacht habt und auf Fehlersuche gegangen seid. Ihr könnt hier an dieser Stelle aber aufhören weiterzugraben.
Ich werd mir eurer Spiel an unserem nächsten Termin bei einem von euren Rechnern nochmal anschauen. Es sieht aber bisher gut aus.
