### ISSUE TITLE
Architekturbewertung

### ISSUE THREAD

**Issue by hauseralex** [derRest/derRest#80]
### Änderbarkeit
Für schnelle Änderbarkeit ist die Klasse _Maze_ zu umfangreich. 
Durch Unterteilung in Subklassen könnte das verbessert werden.

### Wiederverwendbarkeit 
Die Wiederverwendbarkeit ist nicht gegeben, da der Code nicht in Module gegliedert ist.
Dies könnte durch Entwurfsmuster verbessert werden.  

### Ästethik
Die Ästethik ist grundsätzlich schön, sieht aber nicht in jedem Browser gleich aus.
(Möglicher Verbesserungsvorschlag: anderes CSS für IE)

### Benutzbarkeit
Die Benutzbarkeit passt grundsätzlich. 
Lediglich die Steuerung könnte flexibler sein (besipielsweise muss beim Smartphone das Namensfeld ausgewählt sein, um die Pfeiltasten der Tastatur benutzen zu können).

### Funktionalität
Die Funktionalität passt.
Es gibt aber einen Fehler bei den Statuscodes (passen teilweise nicht zum Fehler).

### Lokalisierbarkeit
Die Lokalisierbarkeit stellt momentan keine Hürde dar, da wenig Text vorhanden ist. 
Sollte mehr Text hinzugefügt werden, wäre ein language pack sinnvoll.

### Strapazierfähigkeit
Die Strapazierfähigkeit ist gegeben. 
Bei einer Belastung von 100 simulierten Benutzern gab es keine Probleme.

### Erlernbarkeit
Das Spiel ist einfach zu verstehen. Ein kurzer Hinweis zur Verwendung der Pfeiltasten wäre gut.
(Schön wäre außerdem eine Aufschlüsselung der Punktevergabe)

### Sicherheit
Die API ist komplett offen. Es ist möglich beliebiges JavaScript einzufügen, dadurch kann man sich beispielsweise selbst einen beliebigen Highscorewert eintragen.
Das kann durch einbinden von Tokens und escapen von HTML verhindert werden.

_Team Pluto_

**Comment by felix185** [comment]
![blob](https://cloud.githubusercontent.com/assets/10739344/20525556/4917ff5a-b0c0-11e6-9913-6a9b8d83c71c.png)

Security Issue
